import { supabase } from "@/integrations/supabase/client";

/**
 * Creates an invoice automatically from a completed booking.
 * - Pulls services + addons from the booking
 * - Applies tax rate from site_settings.tax_rate
 * - Invoice number is auto-generated by DB trigger
 */
export const createInvoiceFromBooking = async (booking: any, createdBy?: string | null) => {
  // Read tax rate
  const { data: settings } = await supabase
    .from("site_settings")
    .select("setting_key, setting_value")
    .in("setting_key", ["tax_rate"]);
  const taxRate = Number(settings?.find((s) => s.setting_key === "tax_rate")?.setting_value || 0);

  const addons = Array.isArray(booking.selected_addons) ? booking.selected_addons : [];
  const services = [
    ...(booking.service_type ? [{ title: booking.service_type, price: 0 }] : []),
    ...addons.map((a: any) => ({ title: a.title || "", price: Number(a.price) || 0 })),
  ];

  const subtotal = Number(booking.total_price) || services.reduce((sum, s) => sum + s.price, 0);
  const taxAmount = +(subtotal * (taxRate / 100)).toFixed(2);
  const totalAmount = +(subtotal + taxAmount).toFixed(2);

  const { data, error } = await supabase
    .from("invoices")
    .insert({
      customer_name: booking.name,
      customer_email: booking.email,
      services: services as any,
      subtotal,
      tax_rate: taxRate,
      tax_amount: taxAmount,
      total_amount: totalAmount,
      booking_id: booking.id,
      payment_status: "unpaid",
      created_by: createdBy ?? null,
    } as any)
    .select()
    .single();

  if (error) throw error;
  return data;
};
